### ISSUE TITLE
singular words should be plural where applicable

### ISSUE THREAD

**Issue by ellenjones** [CreativeDino/savanna-portal#4]
Client should be Clients, Invoice should be Invoices, Project should be Projects, etc

This change should be implemented site wide.

Dashboard:
http://creativedinodev.com/savannalandscapes/portal/index.php?/admin/dashboard
• Client button should be "Clients"
• Pending Invoice should be "Pending Invoices"
• Running Project should be "Running Projects"

Header:
• Message should be "Messages"

Left Panel:
• Client should be "Clients"
    • Should we change "Person"?
    \* Should Company be "Companies"?
• Client Project should be "Client Projects"
• Message should be "Messages"
• Note should be "Notes"
• Report should be "Reports"
• Under "Accounting":
    • Client Payment should be "Client Payments"
    • Expense Category should be "Expense Categories"
• Under Report:
    • Project Report should be "Project Reports"
    • Client Report should be "Client Reports"
    • Expense Report should be "Expense Reports"
    • Income Expense Comparison should be "Income Expense Comparisons"

Manage Client:
http://creativedinodev.com/savannalandscapes/portal/index.php?admin/client
• Change header to "Manage Clients"

Company:
http://creativedinodev.com/savannalandscapes/portal/index.php?admin/company
• Change header to "Companies"?

Manage Project:
http://creativedinodev.com/savannalandscapes/portal/index.php?admin/project
• Change header to "Manage Projects"

Expense Category:
http://creativedinodev.com/savannalandscapes/portal/index.php?admin/accounting_expense_category
• Change header to "Expense Categories"

**Comment by ericbjones** [comment]
I did not find person or company to be distracting.  leaving these two

**Comment by ericbjones** [comment]
Income Expense Comparison is one report, not making plural

**Comment by ericbjones** [comment]
changed all.  closing
